apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensitive-app
  namespace: victim-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensitive-app
  template:
    metadata:
      labels:
        app: sensitive-app
    spec:
      containers:
        - name: web
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: sensitive-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensitive-html
  namespace: victim-ns
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif;">
        <h1>SENSITIVE BACKEND</h1>
        <p>This should never be exposed via public ingress.</p>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: sensitive-svc
  namespace: victim-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sensitive-app

