# 1) Default deny all ingress to pods in victim-ns
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: victim-default-deny-ingress
  namespace: victim-ns
spec:
  podSelector: {}          # selects all pods in victim-ns
  policyTypes:
    - Ingress              # only constrain ingress for now
  ingress: []              # no allowed sources → deny all

---
# 2) Allow ingress to sensitive-app ONLY from the ingress-nginx namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress-nginx-to-sensitive
  namespace: victim-ns
spec:
  podSelector:
    matchLabels:
      app: sensitive-app   # from 02-victim.yaml
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          # Optionally further restrict by pod label if you want:
          # podSelector:
          #   matchLabels:
          #     app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: 80

