apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-app
  namespace: attacker-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
        - name: web
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: public-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-html
  namespace: attacker-ns
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif;">
        <h1>PUBLIC BACKEND</h1>
        <p>This is the expected backend for demo.local.</p>
      </body>
    </html>
---
# NOTE: selector is intentionally omitted.
# This service relies on manually managed Endpoints.
apiVersion: v1
kind: Service
metadata:
  name: public-entry
  namespace: attacker-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

