apiVersion: v1
kind: Endpoints
metadata:
  name: public-entry
  namespace: attacker-ns
subsets:
  - addresses:
      - ip: 10.244.0.6   # <-- REPLACE with public-app pod IP
    ports:
      - port: 80
        protocol: TCP

